server:
    port: 8082
    forward-headers-strategy: framework
spring:
    application:
        name: transaction
management:
    health:
        circuitbreakers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
        enabled-by-default: true
    endpoint:
        health:
            show-details: always
        circuitbreakers:
            enabled: true
eureka:
    instance:
        hostname: localhost      
resilience4j.circuitbreaker:
    configs:  
        default:
            register-health-indicator: true
            slidingWindowSize: 5

resilience4j.timelimiter:
    configs:
        default:
            timeoutDuration: 4s
            cancelRunningFuture: true
    