server:
    port: 8084
eureka:
    client:
        service-url:
            defaultZone: http://discovery:8761/eureka/
spring:
    application:
      name: gateway
    cloud:
        gateway:
            routes:
                - id: account
                  uri: lb://account
                  predicates:
                  - Path=/account/**
                - id: transaction
                  uri: lb://transaction
                  predicates:
                    - Path=/transaction/**