
version: "3"
services:
    account:
        build:
            context: ./account-service/
        depends_on:
            - discovery
    transaction:
        build:
            context: ./transaction-service/
        depends_on:
             - discovery
    discovery:
        build:
            context: ./discovery-server/
        ports:
            - "8761:8761"
    gateway:
        build:
            context: ./gateway
        ports:
             - "8084:8084"
    zookeeper:
        image: confluentinc/cp-zookeeper:5.2.1
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SYNC_LIMIT: 2
 
    kafka:
        image: confluentinc/cp-kafka:5.2.1
        ports:
        - "9092:9092"
        depends_on:
        - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
